

industry_href_list = ["https://www.tianyancha.com/search/oc45", "https://www.tianyancha.com/search/oc44",
                      "https://www.tianyancha.com/search/oc46", "https://www.tianyancha.com/search/oc49",
                      "https://www.tianyancha.com/search/oc48", "https://www.tianyancha.com/search/oc47",
                      "https://www.tianyancha.com/search/oc50", "https://www.tianyancha.com/search/oc51",
                      "https://www.tianyancha.com/search/oc52", "https://www.tianyancha.com/search/oc59",
                      "https://www.tianyancha.com/search/oc58", "https://www.tianyancha.com/search/oc57",
                      "https://www.tianyancha.com/search/oc56", "https://www.tianyancha.com/search/oc55",
                      "https://www.tianyancha.com/search/oc60", "https://www.tianyancha.com/search/oc53",
                      "https://www.tianyancha.com/search/oc54", "https://www.tianyancha.com/search/oc04",
                      "https://www.tianyancha.com/search/oc05", "https://www.tianyancha.com/search/oc01",
                      "https://www.tianyancha.com/search/oc02", "https://www.tianyancha.com/search/oc03",
                      "https://www.tianyancha.com/search/oc11", "https://www.tianyancha.com/search/oc12",
                      "https://www.tianyancha.com/search/oc08", "https://www.tianyancha.com/search/oc09",
                      "https://www.tianyancha.com/search/oc06", "https://www.tianyancha.com/search/oc07",
                      "https://www.tianyancha.com/search/oc10", "https://www.tianyancha.com/search/oc35",
                      "https://www.tianyancha.com/search/oc36", "https://www.tianyancha.com/search/oc33",
                      "https://www.tianyancha.com/search/oc34", "https://www.tianyancha.com/search/oc39",
                      "https://www.tianyancha.com/search/oc37", "https://www.tianyancha.com/search/oc38",
                      "https://www.tianyancha.com/search/oc43", "https://www.tianyancha.com/search/oc42",
                      "https://www.tianyancha.com/search/oc41", "https://www.tianyancha.com/search/oc40",
                      "https://www.tianyancha.com/search/oc22", "https://www.tianyancha.com/search/oc23",
                      "https://www.tianyancha.com/search/oc24", "https://www.tianyancha.com/search/oc25",
                      "https://www.tianyancha.com/search/oc26", "https://www.tianyancha.com/search/oc27",
                      "https://www.tianyancha.com/search/oc28", "https://www.tianyancha.com/search/oc29",
                      "https://www.tianyancha.com/search/oc30", "https://www.tianyancha.com/search/oc32",
                      "https://www.tianyancha.com/search/oc31", "https://www.tianyancha.com/search/oc19",
                      "https://www.tianyancha.com/search/oc17", "https://www.tianyancha.com/search/oc18",
                      "https://www.tianyancha.com/search/oc15", "https://www.tianyancha.com/search/oc16",
                      "https://www.tianyancha.com/search/oc13", "https://www.tianyancha.com/search/oc14",
                      "https://www.tianyancha.com/search/oc21", "https://www.tianyancha.com/search/oc20",
                      "https://www.tianyancha.com/search/oc71", "https://www.tianyancha.com/search/oc72",
                      "https://www.tianyancha.com/search/oc73", "https://www.tianyancha.com/search/oc74",
                      "https://www.tianyancha.com/search/oc75", "https://www.tianyancha.com/search/oc78",
                      "https://www.tianyancha.com/search/oc77", "https://www.tianyancha.com/search/oc76",
                      "https://www.tianyancha.com/search/oc79", "https://www.tianyancha.com/search/oc80",
                      "https://www.tianyancha.com/search/oc81", "https://www.tianyancha.com/search/oc62",
                      "https://www.tianyancha.com/search/oc61", "https://www.tianyancha.com/search/oc64",
                      "https://www.tianyancha.com/search/oc65", "https://www.tianyancha.com/search/oc63",
                      "https://www.tianyancha.com/search/oc67", "https://www.tianyancha.com/search/oc66",
                      "https://www.tianyancha.com/search/oc69", "https://www.tianyancha.com/search/oc68",
                      "https://www.tianyancha.com/search/oc70", "https://www.tianyancha.com/search/oc96",
                      "https://www.tianyancha.com/search/oc83", "https://www.tianyancha.com/search/oc84",
                      "https://www.tianyancha.com/search/oc82", "https://www.tianyancha.com/search/oc95",
                      "https://www.tianyancha.com/search/oc94", "https://www.tianyancha.com/search/oc93",
                      "https://www.tianyancha.com/search/oc92", "https://www.tianyancha.com/search/oc91",
                      "https://www.tianyancha.com/search/oc90", "https://www.tianyancha.com/search/oc88",
                      "https://www.tianyancha.com/search/oc89", "https://www.tianyancha.com/search/oc86",
                      "https://www.tianyancha.com/search/oc87", "https://www.tianyancha.com/search/oc85"]

province_list = ['?base=bj', '?base=sh', '?base=tj', '?base=cq', '?base=heb', '?base=sx', '?base=nmg', '?base=ln',
                 '?base=jl', '?base=hlj', '?base=js', '?base=zj', '?base=ah', '?base=fj', '?base=jx', '?base=sd',
                 '?base=hen', '?base=hub', '?base=hun', '?base=gd', '?base=gx', '?base=sc', '?base=gz', '?base=yn',
                 '?base=han', '?base=snx', '?base=gs', '?base=nx', '?base=qh', '?base=xj', '?base=xz', '?base=hk',
                 '?base=mo', '?base=tw']

industry_name_list = ["燃气生产和供应业", "电力、热力生产和供应业", "水的生产和供应业", "建筑安装业", "土木工程建筑业", "房屋建筑业", "建筑装饰和其他建筑业", "批发业", "零售业",
                      "仓储业", "装卸搬运和运输代理业", "管道运输业", "航空运输业", "水上运输业", "邮政业", "铁路运输业", "道路运输业", "渔业", "农、林、牧、渔服务业", "农业",
                      "林业", "畜牧业", "开采辅助活动", "其他采矿业", "黑色金属矿采选业", "有色金属矿采选业", "煤炭开采和洗选业", "石油和天然气开采业", "非金属矿采选业",
                      "专用设备制造业", "汽车制造业", "金属制品业", "通用设备制造业", "计算机、通信和其他电子设备制造业", "铁路、船舶、航空航天和其他运输设备制造业", "电气机械和器材制造业",
                      "金属制品、机械和设备修理业", "废弃资源综合利用业", "其他制造业", "仪器仪表制造业", "造纸和纸制品业", "印刷和记录媒介复制业", "文教、工美、体育和娱乐用品制造业",
                      "石油加工、炼焦和核燃料加工业", "化学原料和化学制品制造业", "医药制造业", "化学纤维制造业", "橡胶和塑料制品业", "非金属矿物制品业", "有色金属冶炼和压延加工业",
                      "黑色金属冶炼和压延加工业", "皮革、毛皮、羽毛及其制品和制鞋业", "纺织业", "纺织服装、服饰业", "酒、饮料和精制茶制造业", "烟草制品业", "农副食品加工业", "食品制造业",
                      "家具制造业", "木材加工和木、竹、藤、棕、草制品业", "租赁业", "商务服务业", "研究和试验发展", "专业技术服务业", "科技推广和应用服务业", "公共设施管理业",
                      "生态保护和环境治理业", "水利管理业", "居民服务业", "机动车、电子产品和日用产品修理业", "其他服务业", "餐饮业", "住宿业", "互联网和相关服务",
                      "软件和信息技术服务业", "电信、广播电视和卫星传输服务", "资本市场服务", "货币金融服务", "其他金融业", "保险业", "房地产业", "国际组织", "卫生", "社会工作",
                      "教育", "基层群众自治组织", "群众团体、社会团体和其他成员组织", "社会保障", "人民政协、民主党派", "国家机构", "中国共产党机关", "体育", "娱乐业",
                      "广播、电视、电影和影视录音制作业", "文化艺术业", "新闻和出版业"]
print(len(industry_href_list))
# sql = "insert into t_industry(industry, href, flag) values ('%s', '%s', '%d')"
#
# for i in range(96):
#     for p in ["", "/p2", "/p3", "/p4", "/p5"]:
#         data = (industry_name_list[i], industry_href_list[i] + p, False)
